# Generated by Django 5.2.9 on 2025-12-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillnest_app', '0006_lessonmaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepublishstatus',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseresource',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentprogressdetail',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='teacherannouncement',
            name='course',
        ),
        migrations.RemoveField(
            model_name='teacherannouncement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='teacherfeedback',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='teachermessage',
            name='course',
        ),
        migrations.RemoveField(
            model_name='teachermessage',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teachermessage',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacherreport',
            name='course',
        ),
        migrations.RemoveField(
            model_name='teacherreport',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='lessonmaterial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='AssignmentSubmission',
        ),
        migrations.DeleteModel(
            name='CoursePublishStatus',
        ),
        migrations.DeleteModel(
            name='CourseResource',
        ),
        migrations.DeleteModel(
            name='StudentProgressDetail',
        ),
        migrations.DeleteModel(
            name='TeacherAnnouncement',
        ),
        migrations.DeleteModel(
            name='TeacherFeedback',
        ),
        migrations.DeleteModel(
            name='TeacherMessage',
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
        migrations.DeleteModel(
            name='TeacherReport',
        ),
    ]
